### ISSUE TITLE
我通过阿里推流获取远端数据，转换成I420数据， 显示处理的是花屏的。 想确认下previewWidth， previewHeight是要传相机的分辨率吗？

### ISSUE THREAD

**Issue by guo-hang** [yangkun19921001/YUVPlay#1]

**Comment by yangkun19921001** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        previewWidth， previewHeight 传 YUV 的宽高
            
        
    
    
        
            
        
    
    
      
    
        
                    
            
                
                    
                            
                                
                            
                            
                                919079498
                            
                    
                        
                            
                                    919079498@qq.com
                            
                        
                
            
        
        
    
    
        签名由
        网易邮箱大师
        定制
    
 
    

    在2020年11月12日 22:05，guo-hang<notifications@github.com> 写道： 





—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by guo-hang** [comment]
感谢， 找到原因了， 是因为rtc返回的YUV数据的宽高会改变引起的， 需要实时计算
